"""Render a finished Strix run into a static HTML site for GitHub Pages.

Reuses the same run-directory parsing the local web viewer and PDF exporter
use (:mod:`strix.interface.viewer.transcript`) so the site never drifts from
what ``strix view`` shows. Output is a single self-contained ``index.html``:
an executive summary with severity counts, the full markdown report, and one
section per finding.

This only ever touches ``strix_runs/<run>`` — no PoC or vulnerability
content is invented or altered here, just re-rendered as HTML.
"""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path
from typing import Any

from markdown_it import MarkdownIt

from strix.core.paths import latest_run_dir
from strix.interface.viewer.transcript import (
    primary_target,
    read_report_markdown,
    read_run_summary,
    read_vulnerabilities,
    severity_counts,
)


_SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#2563eb",
}

_MD = MarkdownIt("commonmark", {"html": False, "linkify": True}).enable(["table", "strikethrough"])

_PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Strix Security Report — {target}</title>
<meta name="robots" content="noindex, nofollow">
<style>
  :root {{
    --bg: #0b0f14; --panel: #121821; --border: #232c38;
    --text: #e6edf3; --muted: #8b98a5; --accent: #22c55e;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 0 16px 64px;
    background: var(--bg); color: var(--text);
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }}
  main {{ max-width: 880px; margin: 0 auto; }}
  header {{ padding: 40px 0 24px; border-bottom: 1px solid var(--border); }}
  header h1 {{ margin: 0 0 8px; font-size: 1.5rem; }}
  header .meta {{ color: var(--muted); font-size: 0.9rem; }}
  .badges {{ display: flex; gap: 10px; margin-top: 20px; flex-wrap: wrap; }}
  .badge {{
    padding: 6px 14px; border-radius: 999px; font-weight: 600; font-size: 0.85rem;
    color: #0b0f14;
  }}
  .badge.status {{ background: var(--accent); color: #0b0f14; }}
  section {{ padding: 32px 0; border-bottom: 1px solid var(--border); }}
  section h2 {{ font-size: 1.2rem; margin-top: 0; }}
  .finding {{ background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
    padding: 20px 24px; margin-bottom: 20px; }}
  .finding-title {{ display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }}
  .finding-title h3 {{ margin: 0; font-size: 1.05rem; }}
  pre {{ background: #0d1218; border: 1px solid var(--border); border-radius: 8px;
    padding: 14px; overflow-x: auto; }}
  code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; }}
  a {{ color: #60a5fa; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid var(--border); padding: 6px 10px; text-align: left; }}
  .empty {{ color: var(--muted); font-style: italic; }}
  footer {{ padding: 24px 0; color: var(--muted); font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<main>
  <header>
    <h1>Strix Security Report</h1>
    <div class="meta">Target: <strong>{target}</strong> &middot; Generated {generated_at}</div>
    <div class="badges">
      <span class="badge status">{status}</span>
      {severity_badges}
    </div>
  </header>

  <section>
    <h2>Executive summary</h2>
    {report_html}
  </section>

  <section>
    <h2>Findings ({finding_count})</h2>
    {findings_html}
  </section>

  <footer>Generated by Strix &middot; not indexed &middot; internal use only</footer>
</main>
</body>
</html>
"""


def _severity_badges(counts: dict[str, int]) -> str:
    parts = []
    for severity, color in _SEVERITY_COLORS.items():
        count = counts.get(severity, 0)
        if count == 0:
            continue
        parts.append(
            f'<span class="badge" style="background:{color}22;color:{color};'
            f'border:1px solid {color}55">{count} {severity}</span>'
        )
    return "\n      ".join(parts) if parts else '<span class="empty">No findings</span>'


def _finding_html(vuln: dict[str, Any]) -> str:
    title = html.escape(str(vuln.get("title") or vuln.get("name") or "Untitled finding"))
    severity = str(vuln.get("severity") or "low").lower()
    color = _SEVERITY_COLORS.get(severity, "#6b7280")
    body_md = str(
        vuln.get("description") or vuln.get("technical_analysis") or vuln.get("details") or ""
    )
    body_html = _MD.render(body_md) if body_md else '<p class="empty">No details recorded.</p>'
    return f"""
    <div class="finding">
      <div class="finding-title">
        <span class="badge" style="background:{color}22;color:{color};border:1px solid {color}55">
          {html.escape(severity)}
        </span>
        <h3>{title}</h3>
      </div>
      {body_html}
    </div>
    """


def render_site(run_dir: Path, output_dir: Path) -> Path:
    summary = read_run_summary(run_dir)
    vulns = [v for v in read_vulnerabilities(run_dir) if isinstance(v, dict)]
    counts = severity_counts(vulns)
    report_md = read_report_markdown(run_dir)

    page = _PAGE_TEMPLATE.format(
        target=html.escape(primary_target(summary) or "unknown target"),
        generated_at=html.escape(str(summary.get("end_time") or summary.get("start_time") or "")),
        status=html.escape(str(summary.get("status") or "unknown")),
        severity_badges=_severity_badges(counts),
        report_html=(
            _MD.render(report_md) if report_md else '<p class="empty">No report generated.</p>'
        ),
        finding_count=len(vulns),
        findings_html="\n".join(_finding_html(v) for v in vulns)
        or '<p class="empty">No findings reported.</p>',
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    index_path = output_dir / "index.html"
    index_path.write_text(page, encoding="utf-8")
    return index_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "run", nargs="?", default=None, help="Run dir under ./strix_runs (default: latest)."
    )
    parser.add_argument(
        "-o", "--output", default="site", help="Output directory for the static site."
    )
    args = parser.parse_args(argv)

    run_dir = Path(args.run) if args.run else latest_run_dir()
    if run_dir is None or not run_dir.is_dir():
        print("No Strix run found under ./strix_runs.", file=sys.stderr)
        return 1

    index_path = render_site(run_dir, Path(args.output))
    print(f"Wrote {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
